### PR TITLE
Kernel version constraints and enabling programs individually

### PR DESCRIPTION
**Pull request by zuzzas**
1. Enable programs invidually. Do not fail whole process if one program fails validation/build. Reflect whether program exists or not in the `ebpf_exporter_enabled_programs` metric.
2. Allows specifying kernel version constraints. So that programs won't run on unexpected kernel versions.

### CODE REVIEW

**Comment by zuzzas** [comment]
@bobrik 
I'll fix tests and write the docs. First I wanted to check whether you like the idea or not?

**Comment by zuzzas** [comment]
@bobrik 
We've been using this patch since May on 200+ Kubernetes clusters. This allows us to write different eBPF programs for different kernel versions. Really useful for dynamic kprobe instrumentation.

Are you interested in accepting this PR and idea as a whole?

**Comment by bobrik** [comment]
My plan is to land #130 first. I think it should unlock kernel constraints for you as well.

Not failing on some programs makes sense. I would postpone it until CO-RE to avoid conflicts.

**Comment by bobrik** [comment]
See #143 for my kernel version constraint thoughts.

Having graceful failure to attach program still sounds good, so feel free to resolve conflicts for that.

**Comment by bobrik** [comment]
I opened #161 that should address graceful handling of failure to attach. Let me know what you think.

**Comment by zuzzas** [comment]
Nice. And I agree with your extensive point about kernel constraints. We'll manage the config externally.

**Pull request closed without merging**
